apiVersion: apps/v1
kind: Deployment
metadata:
  name: ben-coeppicus
  labels:
    app: ben-coeppicus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ben-coeppicus
  template:
    metadata:
      labels:
        app: ben-coeppicus
    spec:
      containers:
        - name: ben-coeppicus
          image: harbor.container.it-scholar.com/seminar/ben-coeppicus:v4
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: ben-coeppicus-html
